INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'muromi', 'Learn AWS Cerified', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'muromi', 'Learn AWS Cerified2', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'muromi', 'Learn AWS Cerified3', CURRENT_DATE(), false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'muromi', 'Learn AWS Cerified4', CURRENT_DATE(), false);
